main: cat.kotuk606.cac.CatAntiCrash
name: CatAntiCrash
api-version: 1.16
version: 1.1
depend: [CatLib,LuckPerms,CatJDA]
author: Kotuk606
commands:
  verify:
    description: Verify admin status
  cacrel:
    description: Reload
permissions:
  catanticrash.bypass_commands:
    description: Bypass command restrictions
    default: false