main: cat.meowkotuk606.anticrash.CatAntiCrash
name: CatAntiCrash
version: 2.1
depend: [CatLib,LuckPerms,CatJDA,ProtocolLib]
softdepend: [UltimateServerProtector]
loadafter: [UltimateServerProtector,LuckPerms,CatLib,CatJDA,ProtocolLib]
author: MeowKotuk606
commands:
  verify:
    description: Admin rights verification
  cacrel:
    description: Reload plugin
permissions:
  catanticrash.bypass.commands:
    description: Bypass command restrictions
    default: false
