main: cat.kotuk606.cac.CatAntiCrash
name: CatAntiCrash
api-version: 1.16
version: 1.0
depend: [CatLib,LuckPerms,CatJDA]
author: Kotuk606
commands:
  verify:
    description: Подтверждение админки
  cacrel:
    description: Перезагрузка
permissions:
  catanticrash.bypass_commands:
    description: Обход запретов на команды
    default: false